drop table if exists userr;
create table userr(
                        id bigint generated by default as identity,
                        first_name varchar(255) not null,
                        last_name varchar(255) not null,
                        age int not null,
                        primary key(id)
);